kanji = [
    ["一", "one"],
    ["右", "right"],
    ["雨", "rain"],
    ["円", "yen, circle"],
    ["王", "king"],
    ["音", "sound"],
    ["下", "below, down"],
    ["火", "fire"],
    ["花", "flower"],
    ["貝", "shellfish"],
    ["学", "study, learning"],
    ["気", "spirit, mind"],
    ["九", "nine"],
    ["休", "rest"],
    ["玉", "jewel"],
    ["金", "gold, money"],
    ["空", "sky, empty"],
    ["月", "moon, month"],
    ["犬", "dog"],
    ["見", "see"],
    ["五", "five"],
    ["口", "mouth"],
    ["校", "school"],
    ["左", "left"],
    ["三", "three"],
    ["山", "mountain"],
    ["子", "child"],
    ["四", "four"],
    ["糸", "thread"],
    ["字", "character, letter"],
    ["耳", "ear"],
    ["七", "seven"],
    ["車", "car, vehicle"],
    ["手", "hand"],
    ["十", "ten"],
    ["出", "exit"],
    ["女", "woman"],
    ["小", "small"],
    ["上", "up"],
    ["森", "forest"],
    ["人", "person"],
    ["水", "water"],
    ["正", "correct"],
    ["生", "life, birth"],
    ["青", "blue"],
    ["夕", "evening"],
    ["石", "stone"],
    ["赤", "red"],
    ["千", "thousand"],
    ["川", "river"],
    ["先", "previous"],
    ["早", "early"],
    ["草", "grass"],
    ["足", "foot"],
    ["村", "village"],
    ["大", "big"],
    ["男", "man"],
    ["竹", "bamboo"],
    ["中", "middle"],
    ["虫", "insect"],
    ["町", "town"],
    ["天", "heaven"],
    ["田", "rice field"],
    ["土", "soil, earth"],
    ["二", "two"],
    ["日", "day, sun"],
    ["入", "enter"],
    ["年", "year"],
    ["白", "white"],
    ["八", "eight"],
    ["百", "hundred"],
    ["文", "sentence"],
    ["木", "tree"],
    ["本", "book"],
    ["名", "name"],
    ["目", "eye"],
    ["立", "stand"],
    ["力", "power"],
    ["林", "grove"],
    ["六", "six"]
]